POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "James Bond",
  "number": "007"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123456789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "987654321"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jon Snow",
  "number": ""
}

